### ISSUE TITLE
左侧文件树不显示创建成功的内容，reload form disk 也无效。

### ISSUE THREAD

**Issue by xiaoyvyv** [longforus/MvpAutoCodePlus#17]
### Describe the bug
创建成功后，不在左侧文件树里显示文件夹内生成的MVP内容。刷新也无效，但实际上已经生成了相关代码。

**Reload form disk** 也无效。
### Error log
```java
java.lang.NoClassDefFoundError: org/jetbrains/android/util/AndroidResourceUtil
	at com.longforus.mvpautocodeplus.maker.LayoutCreatorKt.createLayoutFileForActivityOrFragment(LayoutCreator.kt:70)
	at com.longforus.mvpautocodeplus.maker.LayoutCreatorKt$doCreateLayoutFile$1.run(LayoutCreator.kt:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Desktop (please complete the following information):
 - OS Version: [Win10]
 - Android Studio Version [4.1]
 - Plugin Version [1.4.4]

**Comment by longforus** [comment]
@xiaoyvyv 这个错误是as4.1删掉了这个类，现在已经修好了，jetbrains仓库要先审核，你可以在这里下载：
https://github.com/longforus/MvpAutoCodePlus/releases/tag/v1.4.5

**Comment by xiaoyvyv** [comment]
创建的内容还是不在包下显示，但是没报错了

**Comment by longforus** [comment]
@xiaoyvyv  配置什么的都正确吗?之前成功生成过吗?我这里是没有问题的哦

**Comment by xiaoyvyv** [comment]
配置都是正确的，可能是之前卸载插件重新装的原因。之前都可以正常显示生成的文件，现在不行了。请问一下这个插件的配置文件目录在哪，我删了重新下试试

**Comment by xiaoyvyv** [comment]
我找到不显示生成文件的原因了，
我把项目结构切换到 Project  视图，插件构建的文件可以在文件树正常显示。
我把项目结构切换到 Android 视图，插件构建的文件在左侧文件树中就不显示了。
Android Studio 4.1

**Comment by longforus** [comment]
安卓视图下应该要加一些notify的操作,才会显示出来的,暂时不知道怎么解决,就用project视图吧
